### ISSUE TITLE
Issues with AI and suggestions

### ISSUE THREAD

**Issue by TheRCMGuy** [mrzachhigginsofficial/Arma3-ProjectHedes#8]
This is very nice and a possible replacement of another mod I've been tinkering with in editor but found some issue with it, and some suggestions as well.

- Issue 1: Beside vehicles, AIs that are spawned in either helicopters or garrison points via ambient garrison have their simulations turned off by default.

- Issue 2: With the Garrison module, despite selecting WEST, Opfor AI will spawn (with their simulation disabled still) with some of them dead. Perhaps they are initially making contact with objects within the radius and instantly killing them.

- Suggestion 1: Allow editors to create insertion points for inbound vehicles, something that has been mentioned in the Github.

- Suggestion 2: Adding AI behaviour to the Garrison, in the event mission makers place said garrisons outside of combat zones (idk what the total radius of the Combat Zone Point is).

- Suggestion 3: In regards to the Combat Zone Point, include a radius of the combat zone itself.

- Suggestion 4: Include ground vehicles as part of insertion vehicles.

Overall, a good mod with lots of potential of being a noteworthy addition in most Arma units.

**Comment by Zachary-Higgins-Attic** [comment]
Thanks. I'm going to separate these into individual bugs/ehnancements. I will mention them here and close this issue once I get a chance to make them.

**Comment by Zachary-Higgins-Attic** [comment]
Suggestion 1 tracked here: Combat Zone Insertion Modules #1

**Comment by Zachary-Higgins-Attic** [comment]
I think that's everything. I'm going to mark this as closed. Please check the opened issues when you get a chance. Also, if you don't mind, please reach out to me on discord. I'd like to get your scenario to help reproduce the bugs. Thanks!
